apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: statping
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    ingressClassName: "nginx"
spec:
  tls:
  - hosts:
    - statping.example.com
    secretName: statping-tls
  rules:
  - host: statping.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: statping
          servicePort: http
