apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
  namespace: ingress
spec:
  secretName: ingress-tls
  issuerRef:
    name: letsencrypt
  commonName: example.org
  dnsNames:
  - example.com
  - www.example.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - example.com
      - www.example.com
